name: Go Build and Test

on: [push]

permissions:
  contents: read

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
          echo "GITHUB_TOKEN=${GH_TOKEN}" >> $GITHUB_ENV
          echo "GOPRIVATE=github.com/EO-DataHub" >> $GITHUB_ENV

  go-build:
    uses: EO-DataHub/github-actions/.github/workflows/go-build.yaml@main
    with:
      go-version: "1.22"