name: Go Build and Test

on: [push]

permissions:
  contents: read

jobs:
  setup-auth:
    name: Setup Authentication
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/EO-DataHub
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Configure Git for Authentication
        run: |
          git config --global url."https://$GH_ACCESS_TOKEN@github.com/".insteadOf "https://github.com/"
          echo "GOPRIVATE=github.com/EO-DataHub" >> $GITHUB_ENV
  go-build:
    uses: EO-DataHub/github-actions/.github/workflows/go-build.yaml@main
    with:
      go-version: "1.22"
