name: Go Build and Test

on: [push]

permissions:
  contents: read

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      - name: Set GOPRIVATE
        run: echo "GOPRIVATE=github.com/EO-DataHub" >> $GITHUB_ENV
  go-build:
    uses: EO-DataHub/github-actions/.github/workflows/go-build.yaml@main
    with:
      go-version: "1.22"
    needs: authenticate
