name: Go Build and Test

on: [push]

permissions:
  contents: read

jobs:
  setup-auth:
    name: Authenticate with GitHub App
    runs-on: ubuntu-latest
    steps:
      - name: Install JWT Tool
        run: sudo apt-get install -y jq openssl
      - name: Generate GitHub App Access Token
        env:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
        run: |
          # Create JWT
          now=$(date +%s)
          header='{"alg":"RS256","typ":"JWT"}'
          payload="{\"iat\":$((now - 60)),\"exp\":$((now + 600)),\"iss\":${GH_APP_ID}}"
          unsigned_token=$(echo -n "${header}" | openssl base64 -e -A).$(echo -n "${payload}" | openssl base64 -e -A)
          export JWT=$(echo -n "${unsigned_token}" | openssl dgst -sha256 -sign <(echo "${GH_APP_PRIVATE_KEY}") | openssl base64 -e -A)

          # Get Access Token
          export GITHUB_TOKEN=$(curl -s -X POST \
            -H "Authorization: Bearer ${JWT}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations/${GH_APP_INSTALLATION_ID}/access_tokens | jq -r .token)

          # Configure Git for HTTPS Authentication
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          echo "GOPRIVATE=github.com/EO-DataHub" >> $GITHUB_ENV

  go-build:
    name: Build and Test
    needs: setup-auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install dependencies
        run: |
          go mod download
          go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest

