name: Go Build and Test with GitHub App

on: [push]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Install dependencies for token generation
      - name: Install JWT Tools
        run: sudo apt-get install -y jq openssl
      - name: Debug Secrets (Unsafe)
        run: |
          echo "GH_APP_ID: ${{ secrets.GH_APP_ID }}"
          echo "GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}"
          echo "GH_APP_PRIVATE_KEY:"
          echo "${{ secrets.GH_APP_PRIVATE_KEY }}"
      # Authenticate with GitHub App
      - name: Generate GitHub App Access Token
        env:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
        run: |
          echo "Generating JWT for GitHub App..."
          now=$(date +%s)
          header='{"alg":"RS256","typ":"JWT"}'
          payload="{\"iat\":$((now - 60)),\"exp\":$((now + 600)),\"iss\":${GH_APP_ID}}"

          unsigned_token=$(echo -n "${header}" | openssl base64 -e -A).$(echo -n "${payload}" | openssl base64 -e -A)
          export JWT=$(echo -n "${unsigned_token}" | openssl dgst -sha256 -sign <(echo "${GH_APP_PRIVATE_KEY}") | openssl base64 -e -A)

          echo "Requesting Access Token..."
          export GITHUB_TOKEN=$(curl -s -X POST \
            -H "Authorization: Bearer ${JWT}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations/${GH_APP_INSTALLATION_ID}/access_tokens | jq -r .token)

          if [ "$GITHUB_TOKEN" == "null" ]; then
            echo "Failed to generate GITHUB_TOKEN. Check app permissions and installation ID."
            exit 1
          fi

          echo "Access token generated."

          # Configure Git for HTTPS authentication
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

      # Set Go environment for private modules
      - name: Configure Go Environment
        run: |
          go env -w GOPRIVATE=github.com/EO-DataHub

      # Install Go dependencies
      - name: Install Dependencies
        run: |
          echo "Downloading Go modules..."
          go mod tidy
          go mod download

      # Debug Git Access
      - name: Debug Git Access
        run: |
          echo "Testing repository access..."
          git ls-remote https://github.com/EO-DataHub/eodhp-workspace-controller.git
